In [8]:
import mysql.connector
conn=mysql.connector.connect(user='root',password='Dipak@123',host='localhost',database='new1')
qur='CREATE TABLE student5(name VARCHAR(250), mobno VARCHAR(11), dept VARCHAR(10), email VARCHAR(45))'
mycur=conn.cursor()
mycur.execute(qur)
mycur.close()
conn.close()

ProgrammingError: 1050 (42S01): Table 'student5' already exists

In [2]:
import mysql.connector
from tkinter import *
from tkinter import messagebox
from tkinter import ttk


def show():
    conn=mysql.connector.connect(user='root',password='Dipak@123',host='localhost',database='new1')
    qur='select * from student5'  
        
    mycur=conn.cursor()
    mycur.execute(qur)
    result=mycur.fetchall()
    for i in result:
        treev.insert('','end', values=(i[0],i[1],i[2],i[3]))
            
   

       
        
def add():
    name=n1.get()
    mobno=m1.get()
    dept=d1.get()
    email=e1.get()
    if (name=="" or mobno=="" or dept=="" or email==""):
        messagebox.showinfo("Student info","all fields required to fill")
    
    else:
        conn=mysql.connector.connect(user='root',password='Dipak@123',host='localhost',database='new1')
        qur='INSERT INTO student5(name,mobno,dept,email) values("%s","%s","%s","%s")'%(name,mobno,dept,email)  
        # this values are inserted into .get method
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo("student info","Submitted")
        n1.set('')
        m1.set('')
        d1.set('')
        e1.set('')
        
        
            ##  NEW
        
        
        
def result():
    root=Tk()
    root.configure(bg='white')
    root.title('Result')
    root.geometry('500x400')
    
    
    
    def disp():
        rel=relent.get()
        if rel=="":
                messagebox.showinfo("Student info","all fields required to fill")
        
        else:
            conn=mysql.connector.connect(user='root',password='Dipak@123',host='localhost',database='new1')
            qur='select mobno from student5 where name="s"'%(rel)  
        
            mycur=conn.cursor()
            mycur.execute(qur)
            result=mycur.fetchone()
            new.config(text=result[0])
            relent.delete(0,'end')
            
    
       
            
        
    #rc=StringVar()    
    
    rel=Label(root,text='Enter the name of student',bd=5,relief='ridge',bg='orange',width=20,fg='black',font=('times new roman',12,'bold'))
    rel.place(x=10,y=40)

    
    
    rc=StringVar()
    new=StringVar()
    relent=Entry(root,bd=5,relief='ridge',bg='red',width=40,textvariable=rc,fg='black',font=('times new roman',12,'bold'))
    relent.place(x=200,y=40)
    
    relbtn=Button(root,text='Show Result',width=20,command=disp).place(x=200,y=900)
    
    
    
    
    new=Label(root,text='Marks',bd=5,relief='ridge',bg='purple',width=20,fg='black',font=('times new roman',12,'bold')).place(x=10,y=200)
    new1=Entry(root,bd=5,relief='ridge',bg='red',width=40,textvariable=new,fg='black',font=('times new roman',12,'bold'))
    new1.place(x=200,y=40)
    
    result.mainloop()    #(????????????????????????)
        
        
        
        
           #####
        
    
    
    
def delete():
    deldata=dbn.get()
    if (deldata==""):
        messagebox.showinfo("Student info","all fields required to fill")
    
    else:
        conn=mysql.connector.connect(user='root',password='Dipak@123',host='localhost',database='new1')
        qur='DELETE FROM student5 where name="%s"'%(deldata)  
        # this values are inserted into .get method
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo("student info","Deleted")
        tt.set('')
    
    

    
def clear():
    treev.delete(*treev.get_children())

def update():
    name=n1.get()
    mobno=m1.get()
    dept=d1.get()
    email=e1.get()
    if (name=="" or mobno=="" or dept=="" or email==""):
        messagebox.showinfo("Student info","all fields required to fill")
    
    else:
        conn=mysql.connector.connect(user='root',password='Dipak@123',host='localhost',database='new1')
        qur='UPDATE student5 where SET mobno="%s", dept="%s", email="%s" where name="%s"'%(mobno,dept,email,name) 
        # this values are inserted into .get method
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo("student info","Submitted")
        n1.set('')
        m1.set('')
        d1.set('')
        e1.set('')
    

    
def select():
    rs=updata.get()
    if(rs==""):
        messagebox.showinfo("Student info","all fields required to fill")
    
    else:
        conn=mysql.connector.connect(user='root',password='Dipak@123',host='localhost',database='new1')
        qur='SELECT * from student5 where name="%s"'%(rs)
        mycur=conn.cursor()
        mycur.execute(qur)
        result=mycur.fetchall()
        for i in result:
            ent1.insert(0,i[0])
            ent2.insert(0,i[1])
            ent3.insert(0,i[2])
            ent4.insert(0,i[3])
        
        updata.set('')
        
    
        
        
        
    
    
    
    
    

win=Tk()
win.title('STUDENT MANAGEMENT SYSTEM')
win.iconbitmap('image.ico')
win.minsize(width=800,height=600)
win.configure(bg='skyblue')


n1=StringVar()
m1=StringVar()
d1=StringVar()
e1=StringVar()
dbn=StringVar()
updata=StringVar()




                                               # Lables


l1=Label(win,text='STUDENT MANAGEMENT SYSTEM',bd=5,relief='ridge',bg='red',fg='black',font=('times new roman',16,'bold'))
l1.place(x=268,y=40)

l2=Label(win,text='Name',bd=5,relief='ridge',bg='orange',width=20,fg='black',font=('times new roman',12,'bold'))
l2.place(x=190,y=100)

l3=Label(win,text='Mobile No',bd=5,relief='ridge',bg='orange',width=20,fg='black',font=('times new roman',12,'bold'))
l3.place(x=190,y=150)

l4=Label(win,text='Department',bd=5,relief='ridge',bg='orange',width=20,fg='black',font=('times new roman',12,'bold'))
l4.place(x=190,y=200)

l5=Label(win,text='E-Mail Id',bd=5,relief='ridge',bg='orange',width=20,fg='black',font=('times new roman',12,'bold'))
l5.place(x=190,y=250)

l6=Label(win,text='Delete by name',bd=5,relief='ridge',bg='orange',width=20,fg='black',font=('times new roman',12,'bold'))
l6.place(x=190,y=350)

l7=Label(win,text='Update by name',bd=5,relief='ridge',bg='orange',width=20,fg='black',font=('times new roman',12,'bold'))
l7.place(x=190,y=450)





                                            #Entry Box

ent1=Entry(win,bd=5,relief='ridge',bg='White',width=40,textvariable=n1,fg='black',font=('times new roman',12,'bold'))
ent1.place(x=385,y=100)

ent2=Entry(win,bd=5,relief='ridge',bg='White',width=40,textvariable=m1,fg='black',font=('times new roman',12,'bold'))
ent2.place(x=385,y=150)

ent3=Entry(win,bd=5,relief='ridge',bg='White',width=40,textvariable=d1,fg='black',font=('times new roman',12,'bold'))
ent3.place(x=385,y=200)

ent4=Entry(win,bd=5,relief='ridge',bg='White',width=40,textvariable=e1,fg='black',font=('times new roman',12,'bold'))
ent4.place(x=385,y=250)

ent5=Entry(win,bd=5,relief='ridge',bg='White',width=40,textvariable=dbn,fg='black',font=('times new roman',12,'bold'))
ent5.place(x=385,y=350)

ent6=Entry(win,bd=5,relief='ridge',bg='White',width=40,textvariable=updata,fg='black',font=('times new roman',12,'bold'))
ent6.place(x=385,y=450)



                                    #Buttons



showbtn=Button(win,text='Show',width=20,command=show).place(x=150,y=300)
addbtn=Button(win,text='Add',width=20,command=add).place(x=300,y=300)
exitbtn=Button(win,text='Exit',width=20,command=win.destroy).place(x=450,y=300)     # for exit the window we can use the win.destroy command this cooamd directly exit the window
deletebtn=Button(win,text='Delete',width=20,command=delete).place(x=350,y=400)
selectbtn=Button(win,text='Select',width=20,command=select).place(x=250,y=500)
updatebtn=Button(win,text='Update',width=20,command=update).place(x=450,y=500)
resultbtn=Button(win,text='Result',width=20,command=result).place(x=450,y=600)

treev=ttk.Treeview(win,selectmode='browse',height=30)
treev.place(x=900,y=100,width=600)


treev["columns"] = ("1","2","3","4")
treev["show"] = 'headings'
treev.column('1',width=90,anchor='c')
treev.column('2',width=90,anchor='se')
treev.column('3',width=90,anchor='se')
treev.column('4',width=90,anchor='se')


treev.heading('1',text='Name')
treev.heading('2',text='mobile No')
treev.heading('3',text='Department')
treev.heading('4',text='E-Mail Id')



clearbtn=Button(win,text='clear',width=28,command=clear).place(x=1000,y=560)




win.mainloop()

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "<ipython-input-2-69c41e150a76>", line 97, in result
    result.mainloop()    #(????????????????????????)
AttributeError: 'function' object has no attribute 'mainloop'